src/main/java/model/ActiveStatus.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model;

/**
 *
 * @author bzolt
 */
public enum ActiveStatus {
        ACTIVE("Active"),
        INACTIVE("Inactive");

        private final String act;

        ActiveStatus(String act) {
            this.act = act;
        }

        public String getAcitvity() {
            return act;
        }
        
}

src/main/java/model/Car.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 *
 * @author bzolt
 */
@Entity
@Table(name = "CAR")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "Car.findAll", query = "SELECT c FROM Car c")})
public class Car implements Serializable {

    private static final long serialVersionUID = 1L;
    @Id
    @Basic(optional = false)
    @NotNull
    @SequenceGenerator(name = "DRIVER_ID_SEQ",sequenceName = "DRIVER_ID_SEQ",allocationSize=1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DRIVER_ID_SEQ")
    @Column(name = "ID")
    private Integer id;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 40)
    @Column(name = "NAME")
    private String name;
    @Basic(optional = false)
    @NotNull
    @Enumerated(EnumType.STRING)
    @Column(name = "REQUIRED_LICENSE")
    private License requiredLicense;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 15)
    @Column(name = "PLATE_NUMBER")
    private String plateNumber;
    @Basic(optional = false)
    @NotNull
    @Enumerated(EnumType.STRING)
    @Column(name = "CAR_TYPE")
    private CarType type;
    @Basic(optional = false)
    @NotNull
    @Enumerated(EnumType.STRING)
    @Column(name = "CAR_CONDITION")
    private Condition condition;
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "car")
    private List<Shipping> shippingList;
    
    public enum Condition {
        WORKING("Working"),
        NOT_WORKING("Not working");

        private final String cond;

        Condition(String cond) {
            this.cond = cond;
        }

        public String getCondition() {
            return cond;
        }
        
    }
    
    public enum License {
        B("B"),
        C("C"),
        D("D");

        private final String license;

        License(String license) {
            this.license = license;
        }

        public String getLicenseType() {
            return license;
        }
        
    }
    
    public enum CarType {
        VAN("Van"),
        LORRY("Lorry"),
        BUS("Bus"),
        SEDAN("Sedan"),
        TRUCK("Truck"),
        OTHER("Other");

        private final String carType;

        CarType(String carType) {
            this.carType = carType;
        }

        public String getCarType() {
            return carType;
        }
        
    }

    public Car() {
        this.shippingList = new ArrayList<>();
    }

    public Car(Integer id) {
        this.id = id;
    }


    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public License getRequiredLicense() {
        return requiredLicense;
    }

    public void setRequiredLicense(License requiredLicense) {
        this.requiredLicense = requiredLicense;
    }

    @XmlTransient
    public List<Shipping> getShippingList() {
        return shippingList;
    }

    public void setShippingList(List<Shipping> shippingList) {
        this.shippingList = shippingList;
    }

    public String getPlateNumber() {
        return plateNumber;
    }

    public void setPlateNumber(String plateNumber) {
        this.plateNumber = plateNumber;
    }

    public CarType getType() {
        return type;
    }

    public void setType(CarType type) {
        this.type = type;
    }

    public Condition getCondition() {
        return condition;
    }

    public void setCondition(Condition condition) {
        this.condition = condition;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 19 * hash + Objects.hashCode(this.id);
        hash = 19 * hash + Objects.hashCode(this.name);
        hash = 19 * hash + Objects.hashCode(this.requiredLicense);
        hash = 19 * hash + Objects.hashCode(this.plateNumber);
        hash = 19 * hash + Objects.hashCode(this.type);
        hash = 19 * hash + Objects.hashCode(this.condition);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Car other = (Car) obj;
        if (!Objects.equals(this.name, other.name)) {
            return false;
        }
        if (!Objects.equals(this.plateNumber, other.plateNumber)) {
            return false;
        }
        if (!Objects.equals(this.id, other.id)) {
            return false;
        }
        if (this.requiredLicense != other.requiredLicense) {
            return false;
        }
        if (this.type != other.type) {
            return false;
        }
        if (this.condition != other.condition) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "Car{" + "id=" + id + '}';
    }
    
    
}

src/main/java/model/OrderStatus.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model;

/**
 *
 * @author bzolt
 */
public enum OrderStatus {
        ACTIVE("Active"),
        STORNO("Storno"),
        DONE("Done");

        private final String stat;

        OrderStatus(String stat) {
            this.stat = stat;
        }

        public String getStatus() {
            return stat;
        }
}

src/main/java/control/AuthenticationController.java
package control;

import facade.MarketUserFacade;
import java.io.IOException;
import java.io.Serializable;
import java.security.Principal;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;
import model.MarketUser;

@Named(value = "authenticationController")
@SessionScoped
public class AuthenticationController extends UserController implements Serializable {

    private static final long serialVersionUID = 1685823449195612778L;
    private static Logger log = Logger.getLogger(AuthenticationController.class.getName());

    @EJB
    private MarketUserFacade userFacade;

    private MarketUser user;
    private MarketUser loginUser;
    private String confirmPassword;
    private String phoneNumber;

    private String script;

    public AuthenticationController() {
    }

    public void init() throws IOException {
        alreadyLoggedIn();
        script = "document.getElementById('loginForm:validatorMessage').style.display = 'none'";
        FacesContext.getCurrentInstance().getPartialViewContext().getRenderIds().add("loginForm:script");
        user = new MarketUser();
        loginUser = null;
    }

    public void register() throws IOException {
        user.setUserRole("user");
        boolean alreadyInUse = false;
        for (MarketUser userIt : userFacade.findAll()) {
            if (userIt.getEmail().equals(user.getEmail())) {
                alreadyInUse = true;
            }
        }
        if (!alreadyInUse) {
            try {
                userFacade.createUser(user, phoneNumber);
                log.info("New user created");
                FacesContext.getCurrentInstance().getExternalContext().redirect("registration_successful.xhtml");
            } catch (Exception ex) {

            }
        } else {
            addErrorMessageForComponent("registrationForm:email","Email already in use!");
        }

    }

    public void login() throws IOException {
        FacesContext context = FacesContext.getCurrentInstance();
        HttpServletRequest request = (HttpServletRequest) context.getExternalContext().getRequest();
        try {
            request.login(user.getEmail(), user.getPwd());
        } catch (ServletException e) {
            script = "document.getElementById('loginForm:validatorMessage').style.display = 'flex'";
            FacesContext.getCurrentInstance().getPartialViewContext().getRenderIds().add("loginForm:script");
            return;
        }
        Principal principal = request.getUserPrincipal();
        loginUser = userFacade.findByEmail(principal.getName());
        log.info("Authentication done for user: " + principal.getName());
        ExternalContext externalContext = FacesContext.getCurrentInstance().getExternalContext();
        Map<String, Object> sessionMap = externalContext.getSessionMap();
        sessionMap.put("User", loginUser);
        FacesContext.getCurrentInstance().getExternalContext().redirect("user_data.xhtml");
    }

    public void logout() throws IOException {
        FacesContext context = FacesContext.getCurrentInstance();
        HttpServletRequest request = (HttpServletRequest) context.getExternalContext().getRequest();
        try {
            loginUser = null;
            request.logout();
            // clear the session
            ((HttpSession) context.getExternalContext().getSession(false)).invalidate();
            ExternalContext externalContext = FacesContext.getCurrentInstance().getExternalContext();
            Map<String, Object> sessionMap = externalContext.getSessionMap();
            sessionMap.remove("User");
            FacesContext.getCurrentInstance().getExternalContext().redirect("index.xhtml");
        } catch (ServletException e) {
            log.log(Level.SEVERE, "Failed to logout user!", e);
        }
    }

    public String getConfirmPassword() {
        return confirmPassword;
    }

    public void setConfirmPassword(String confirmPassword) {
        this.confirmPassword = confirmPassword;
    }

    public MarketUser getUser() {
        return user;
    }

    public void setUser(MarketUser user) {
        this.user = user;
    }

    public String getScript() {
        return script;
    }

    public void setScript(String script) {
        this.script = script;
    }

    public MarketUser getLoginUser() {
        return loginUser;
    }

    public void setLoginUser(MarketUser loginUser) {
        this.loginUser = loginUser;
    }

    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

}

src/main/java/control/CarController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package control;

import facade.CarFacade;
import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import javax.ejb.EJB;
import javax.faces.context.FacesContext;
import javax.faces.view.ViewScoped;
import javax.inject.Named;
import model.Car;

/**
 *
 * @author bzolt
 */
@Named(value = "carController")
@ViewScoped
public class CarController extends UserController implements Serializable {

    private static final long serialVersionUID = 1685823449195612771L;

    @EJB
    CarFacade carFacade;

    private String filteredName;
    private String filteredPlate;
    private Car.Condition filteredCondition;
    private Car car;

    private List<Car> carList;

    public CarController() {
    }

    public void init() throws IOException {
        if (getLoggedInUser() == null) {
            FacesContext.getCurrentInstance().getExternalContext().redirect("index.xhtml");
        } else if (getLoggedInUser().getId() == null) {
            FacesContext.getCurrentInstance().getExternalContext().redirect("index.xhtml");
        } else {
            filter();
        }
    }

    public void initExistingCar() throws IOException {
        if (getLoggedInUser() == null) {
            FacesContext.getCurrentInstance().getExternalContext().redirect("index.xhtml");
        } else if (getLoggedInUser().getId() == null) {
            FacesContext.getCurrentInstance().getExternalContext().redirect("index.xhtml");
        } else {
            Map<String, String> params = FacesContext.getCurrentInstance().
                    getExternalContext().getRequestParameterMap();
            String carId = params.get("car");
            car = carFacade.findById(Integer.parseInt(carId));
        }
    }

public void initNewCar() throws IOException {
        if (getLoggedInUser() == null) {
            FacesContext.getCurrentInstance().getExternalContext().redirect("index.xhtml");
        } else if (getLoggedInUser().getId() == null) {
            FacesContext.getCurrentInstance().getExternalContext().redirect("index.xhtml");
        } else {
            car = new Car();
        }
    }

    public void filter() {
        carList = carFacade.findAll();
        List<Car> tempCarList = new ArrayList<>();
        if (filteredName != null) {
            if (!filteredName.isEmpty()) {
                for (Car car : carList) {
                    if (!car.getName().toUpperCase().contains(filteredName.toUpperCase())) {
                        tempCarList.add(car);
                    }
                }
            }
        }
        if (filteredPlate != null) {
            if (!filteredPlate.isEmpty()) {
                filteredPlate = filteredPlate.toUpperCase();
                for (Car car : carList) {
                    if (!car.getPlateNumber().contains(filteredPlate)) {
                        tempCarList.add(car);
                    }
                }
            }
        }
        if (filteredCondition != null) {
            for (Car car : carList) {
                if (!car.getCondition().equals(filteredCondition)) {
                    tempCarList.add(car);
                }
            }
        }
        carList.removeAll(tempCarList);
    }

    public void editCar() throws IOException {
        carFacade.edit(car);
        FacesContext.getCurrentInstance().getExternalContext().redirect("view_car.xhtml?car=" + car.getId());
    }

    public void newCar() throws IOException {
        carFacade.create(car);
        FacesContext.getCurrentInstance().getExternalContext().redirect("cars.xhtml");
    }

    public Car.Condition[] allConditions() {
        return Car.Condition.values();
    }

    public Car.CarType[] allTypes() {
        return Car.CarType.values();
    }

    public Car.License[] allLicenses() {
        return Car.License.values();
    }

    public String getFilteredName() {
        return filteredName;
    }

    public void setFilteredName(String filteredName) {
        this.filteredName = filteredName;
    }

    public String getFilteredPlate() {
        return filteredPlate;
    }

    public void setFilteredPlate(String filteredPlate) {
        this.filteredPlate = filteredPlate;
    }

    public Car.Condition getFilteredCondition() {
        return filteredCondition;
    }

    public void setFilteredCondition(Car.Condition filteredCondition) {
        this.filteredCondition = filteredCondition;
    }

    public List<Car> getCarList() {
        return carList;
    }

    public void setCarList(List<Car> carList) {
        this.carList = carList;
    }

    public Car getCar() {
        return car;
    }

    public void setCar(Car car) {
        this.car = car;
    }

}

src/main/webapp/cars.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:b="http://bootsfaces.net/ui"
                xmlns:p="http://primefaces.org/ui"
                template="home.xhtml">

    <ui:define name="cars">
        <h:head>
            <title> MarketManager | Cars </title>
        </h:head>

        <h:body>
            <f:view>

                <f:metadata>
                    <f:viewAction action="#{carController.init()}" />
                </f:metadata>


                <h:form id = "carForm" >

                    <b:growl id="growl" allowDismiss="true" />  

                    <h3>
                        <h:outputText value="Cars"/>
                    </h3>

                    <b:button look="primary" outcome="new_car" value ="New Car"/> 

                    <br/><br/>

                    <h:outputScript library="js" name="main.js" />

                    <b:button icon-awesome="fas fa-sort-down" icon-align="right" style="width:9%;display: inline;background-color: #3c3f41; color: white" id="filterb1"  value="Filter list" onclick="show('carForm:filter', 'carForm:filterb1', 'carForm:filterb2')" />
                    <b:button icon-awesome="fas fa-sort-up" icon-align="right" style="width:9%;display: none;background-color: #3c3f41; color: white" id="filterb2"  value="Filter list" onclick="show('carForm:filter', 'carForm:filterb1', 'carForm:filterb2')" />
                    <h:panelGroup id ="filter"   style="display : none;">
                        <p:panelGrid columns="2">
                            <h:outputLabel value="Name" for="carName" />
                            <h:inputText value="#{carController.filteredName}" id="carName"  />

                            <h:outputLabel value="Plate number" for="plateNumber" />
                            <h:inputText value="#{carController.filteredPlate}" id="plateNumber"  />

                            <h:outputLabel value="Condition" for="conditionSelector" />
                            <b:selectOneMenu style="width: 96%" id="conditionSelector"  value="#{carController.filteredCondition}">
                                <f:selectItem itemValue="#{null}"/>
                                <f:selectItems value="#{carController.allConditions()}" var="filteredCondition" itemLabel="#{filteredCondition.condition}" itemValue="#{filteredCondition}" />
                            </b:selectOneMenu>
                        </p:panelGrid>
                        <b:commandButton look="success" value="Filter" ajax="true" update="carForm:carsTable" actionListener="#{carController.filter()}"/> 
                    </h:panelGroup>

                    <br/><br/>

                    <b:dataTable lang="eng" id ="carsTable" markSearchResults="true" paginated="true" striped="true" select="false" var="car" value="#{carController.carList}">
                        <b:dataTableColumn label="Name">
                            <h:outputText value="#{car.name}"/>
                        </b:dataTableColumn>
                        <b:dataTableColumn label="Type">
                            <h:outputText value="#{car.type.carType}"/>
                        </b:dataTableColumn>
                        <b:dataTableColumn label="Plate number">
                            <h:outputText value="#{car.plateNumber}"/>
                        </b:dataTableColumn>
                        <b:dataTableColumn label="Required license" style="width:20%">
                            <h:outputText value="#{car.requiredLicense.licenseType}"/>
                        </b:dataTableColumn>
                        <b:dataTableColumn label="Condition" style="width:10%">
                            <h:outputText value="#{car.condition.condition}"/>
                        </b:dataTableColumn>
                        <b:dataTableColumn label="Actions">
                            <b:button look="info" value="View" icon-awesome="fas fa-eye" outcome="view_car.xhtml?car=#{car.id}" />
                            <b:button look="primary" value="Edit" icon-awesome="fas fa-pencil" outcome="edit_car.xhtml?car=#{car.id}" />
                        </b:dataTableColumn>
                    </b:dataTable>

                </h:form>

            </f:view>

        </h:body>

    </ui:define>

</ui:composition>

src/main/webapp/edit_employee.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                xmlns:b="http://bootsfaces.net/ui"
                template="home.xhtml">

    <ui:define name="edit_employee">

        <h:head>
            <title> MarketManager | Edit Employee </title>
        </h:head>

        <h:body>
            <f:view>

                <f:metadata>
                    <f:viewAction action="#{employeeController.initExistingEmployee()}" />
                </f:metadata>

                <h:form id = "employeeEditForm" >
                    
                    <p:resizable for="employeeEditGrid" />
                    <h3>
                        <h:outputText value="Edit Employee"/>
                    </h3>

                    <p:panelGrid id ="employeeEditGrid" columns="2">

                        <h:outputLabel value="Name" for="name" />
                        <h:inputText id="name" value="#{employeeController.employee.name}" required="true" requiredMessage="The Name field is required."/>


                        <h:outputLabel value="Email" for="email" />
                        <h:inputText id="email" value="#{employeeController.employee.email}"  required="true" requiredMessage="The Email field is required.">
                            <f:validator validatorId="emailValidator" />
                        </h:inputText>


                        <h:outputLabel value="Phone number" for="phone" />
                        <h:inputText id="phone" value="#{employeeController.employee.phoneNumber}" required="true" requiredMessage="The Phone number field is required."/>


                        <h:outputLabel value="Position" for="positionSelector" />
                        <p:selectOneMenu id="positionSelector" filter="true" filterMatchMode="startsWith"  value="#{employeeController.employee.position}" required="true" requiredMessage="Selecting employee position is mandatory">
                            <f:selectItems value="#{employeeController.allPositions()}" var="position" itemLabel="#{position.position}" itemValue="#{position}" noSelectionValue="#{null}"/>
                        </p:selectOneMenu>
                        
                        <h:outputLabel value="Status" for="statusSelector" />
                        <p:selectOneMenu id="statusSelector" value="#{employeeController.employee.activeStatus}" >
                            <f:selectItems value="#{employeeController.allActiveStatus()}" var="activeStatus" itemLabel="#{activeStatus.acitvity}" itemValue="#{activeStatus}" />
                        </p:selectOneMenu>


                        <h:outputLabel value="Admin" for="adminCheck" />
                        <h:selectBooleanCheckbox value="#{employeeController.adminCheckBox}"  id="adminCheck"/>

                    </p:panelGrid>
                    <h:panelGrid columns="1">
                        <h:message id="m1" for="name" style="color:red"/> 
                        <h:message id="m2" for="email" style="color:red"/> 
                        <h:message id="m3" for="phone" style="color:red"/> 
                        <h:message id="m4" for="positionSelector" style="color:red"/> 
                    </h:panelGrid>

                    <br/>

                    <b:commandButton look="success" value ="Save" actionListener="#{employeeController.editEmployee()}" update="@form"/>
                    
                    <br/><br/>
                    <b:button value ="Back to Employees" outcome="employees" icon-awesome="fas fa-chevron-left"/>

                </h:form>

            </f:view>

        </h:body>

    </ui:define>

</ui:composition>

src/main/webapp/edit_user.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                xmlns:b="http://bootsfaces.net/ui"
                template="home.xhtml">

    <ui:define name="edit_user">
        
        <h:head>
                <title> MarketManager | Edit User </title>
        </h:head>
        
        <h:body>
            <f:view>

                <f:metadata>
                    <f:viewAction action="#{employeeController.initExistingEmployee()}" />
                </f:metadata>

                <h:form id = "employeeEditForm" >
                    
                    <p:resizable for="employeeEditGrid" />

                    <h3>
                        <h:outputText value="Edit User"/>
                    </h3>

                    <p:panelGrid id ="employeeEditGrid" columns="2">

                        <h:outputLabel value="Name" for="name" />
                        <h:inputText id="name" value="#{employeeController.employee.name}" required="true" requiredMessage="The Name field is required."/>

                        <h:outputLabel value="Email" for="email" />
                        <h:inputText id="email" value="#{employeeController.employee.email}"  required="true" requiredMessage="The Email field is required.">
                            <f:validator validatorId="emailValidator" />
                        </h:inputText>

                        <h:outputLabel value="Phone number" for="phone" />
                        <h:inputText id="phone" value="#{employeeController.employee.phoneNumber}" required="true" requiredMessage="The Phone number field is required."/>
                        
                        <h:outputLabel  rendered="#{employeeController.isUserInRole('admin')}" value="Position" for="positionSelector" />
                        <p:selectOneMenu  rendered="#{employeeController.isUserInRole('admin')}" id="positionSelector" filter="true" filterMatchMode="startsWith"  value="#{employeeController.employee.position}" required="true" requiredMessage="Selecting employee position is mandatory">
                            <f:selectItems value="#{employeeController.allPositions()}" var="position" itemLabel="#{position.position}" itemValue="#{position}" noSelectionValue="#{null}"/>
                        </p:selectOneMenu>
                        
                        <h:outputLabel for="statusSelector" value="Status" />
                        <p:selectOneMenu id="statusSelector" value="#{employeeController.employee.activeStatus}" >
                            <f:selectItems value="#{employeeController.allActiveStatus()}" var="activeStatus" itemLabel="#{activeStatus.acitvity}" itemValue="#{activeStatus}" />
                        </p:selectOneMenu>
                        
                        <h:outputLabel value="New password" for="password" />
                        <h:inputSecret id="password" value="#{employeeController.newUserPwd}" />

                    </p:panelGrid>
                    <h:outputText  style= "color: lightcoral" value = "If you don't wish to channge your password just leave the field empty" />
                    <br/><br/>
                    
                    <h:panelGrid columns="1">
                        <h:message id="m1" for="name" style="color:red"/> 
                        <h:message id="m2" for="email" style="color:red"/> 
                        <h:message id="m3" for="phone" style="color:red"/> 
                        <h:message id="m4"  rendered="#{employeeController.isUserInRole('admin')}" for="positionSelector" style="color:red"/> 
                    </h:panelGrid>
                    <b:commandButton look="success" value ="Save" actionListener="#{employeeController.editUser()}" update="@form"/>
                    
                    <br/><br/>
                    <b:button value ="Back to Home page" outcome="user_data" icon-awesome="fas fa-chevron-left"/>

                </h:form>

            </f:view>

        </h:body>

    </ui:define>

</ui:composition>